  #---------------------------------#
  #      general configuration      #
  #---------------------------------#

  init:
    # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
    - ps: >-
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        }
        else
        {
          Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
        }
        
    -ps: Write-Output $env:APPVEYOR_BUILD_NUMBER
        
    -ps: Write-Output $env:APPVEYOR_VERSION_NUMBER

  # version format
  version: "{build}"
  # branches to build
  branches:
    # whitelist
    only:
      - master

  # Skipping commits with particular message or from specific user
  skip_commits:
    message: skip_deployment
  # Skipping commits affecting specific files (GitHub only). More details here: https://www.appveyor.com/docs/appveyor-yml
    files:
    - README.MD

  # Start builds on tags only (GitHub and BitBucket)
  skip_non_tags: true

  #---------------------------------#
  #    environment configuration    #
  #---------------------------------#

  # Build worker image (VM template)
  image: Visual Studio 2015

  # enable patching of AssemblyInfo.* files
  #assembly_info:
  #  patch: true
  #  file: AssemblyInfo.*
  #  assembly_version: "2.2."{build}""
  #  assembly_file_version: "{version}"
  #  assembly_informational_version: "{version}"

  #---------------------------------#
  #       build configuration       #
  #---------------------------------#

  # build platform, i.e. x86, x64, Any CPU. This setting is optional.
  platform: Any CPU
  # build Configuration, i.e. Debug, Release, etc.
  configuration: Release

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: "{build}"
    assembly_file_version: "{build}"
    assembly_informational_version: "{build}"

  build:
  # MSBuild verbosity level
    verbosity: normal

  #to disable automatic tests 
  test: off


  #---------------------------------#
  #      artifacts configuration    #
  #---------------------------------#

  artifacts:
    # pushing a single file with environment variable in path and "Deployment name" specified
    - path: CopyProductCode.Setup\bin\Release\CopyProductCode.Setup.msi
      name: CopyProductCode.Setup_v"{build}".msi

  #---------------------------------#
  #     deployment configuration    #
  #---------------------------------#
  deploy:
      # Deploy to GitHub Releases
    - provider: GitHub
      artifact: CopyProductCode.Setup_v"{build}".msi           # upload all NuGet packages to release assets
      draft: false
      prerelease: false
      on:
        branch: master                # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only

  # to disable deployment
  #deploy: off
